### ISSUE TITLE
Problems with generation of team maps on Mac/VS Code

### ISSUE THREAD

**Issue by schmidthappens** [ContextMapper/context-mapper-examples#18]
Hi Stefan et al.,

I've got some issues with the team map example. I copied https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/insurance-example/Insurance-Example_Team-Map.cml but the result looks like this.

![grafik](https://user-images.githubusercontent.com/57909250/91399272-fd631680-e83d-11ea-8566-143809ef6303.png)

I'm working on Mac OSX with latest VS Code and also tried the Eclipse way, but there I got other issues 😉 .

**Comment by stefan-ka** [comment]
Hi @schmidthappens 

I assume you expected a graphic like in out README, [here](https://github.com/ContextMapper/context-mapper-examples#team-map)? :)

If yes, this is a duplicate of https://github.com/ContextMapper/context-map-generator/issues/5. Unfortunately this is not supported yet... The illustration in that README was originally created manually to illustrate the DSL capabilities. The graphical Context Map generator does not support generating such graphics yet. So, for the current version of @ContextMapper the result you get is actually correct. You see the complete team map, but not which Bounded Contexts are realized by which team.

However, since there are many users complaining about that lately, I will try to implement this soon :)

Sorry, that I cannot give you a better answer right now.

Best regards,
Stefan

**Comment by schmidthappens** [comment]
Alright, thank you for the response and insights. 
If you need help let me know. I worked with Xtext et al. several years, so maybe I can support you here.
I will close this issue as it is a duplicate of https://github.com/ContextMapper/context-mapper-examples#team-map

**Comment by stefan-ka** [comment]
Thanks @schmidthappens, of course contributions (PRs) are always welcome ;)
However, this issue does not affect the DSL (Xtext). We have to enhance https://github.com/ContextMapper/context-map-generator, which is based on Graphviz... But as I said, contributions are always welcome anyway :)
