### ISSUE TITLE
Graphical context map

### ISSUE THREAD

**Issue by fabianboerner** [ContextMapper/context-mapper-examples#27]
Does this example:

/context-mapper-examples/blob/master/src/main/cml/architectural-refactorings/AR-02-Split-Bounded-Context-by-Features/example-output.cml

work with the graphical context map generator?

It only shows the PolicyManagementContext and thats it.

![test_ContextMap](https://user-images.githubusercontent.com/115671732/206580237-dd5ba3f9-b929-4e10-ab5e-0778ab6d367c.png)

**Comment by stefan-ka** [comment]
Hi @fabianboerner 

The output of the context map generator is correct here, yes. Because the `PolicyManagementContext` is the only context that is added to the context map in CML.

This example was designed to illustrate an Architectural Refactoring and not how the context map generator works.

If you need an example for a Context Map I suggest to try it out with one of the following examples:

* https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/ddd-sample/DDD-Sample-Stage-5.cml
* https://github.com/ContextMapper/context-mapper-examples/blob/master/src/main/cml/insurance-example/Insurance-Example-Stage-5.cml

Best regards,
Stefan
